cd ../..
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 500 --filter mean --model Pyraformer
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 1000 --filter mean --model Informer
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 1000 --filter mean --model lstm
## low
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 500 --filter low_pass --model lstm_fcn
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 500 --filter low_pass --model Reformer
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 1000 --filter low_pass --model lstm_fcn
#python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 1000 --filter low_pass --model lstm
python -u run.py --task_name classification --enc_in 12   --is_training 1    --root_path ./   --model_id bone_c   --data bone_drill_c    --e_layers 2 --d_layers 1   --batch_size 16    --d_model 64    --d_ff 64    --top_k 3    --des 'Exp'    --itr 50    --learning_rate 0.0001    --train_epochs 40    --patience 15 --seq_len 500 --filter low_pass --model fcn
